In [59]:
import datetime
import boto3
from io import StringIO

In [76]:
# Create an S3 resource
s3_resource = boto3.resource('s3')
# Your S3 Bucket name
bucket_name = 'aws-datalake-finance'
# Create an S3 client
s3_client = boto3.client('s3')


def save_dolthub_earnings_data(ticker):

    # URL of the DoltHub SQL endpoint
    url = f"https://www.dolthub.com/api/v1alpha1/post-no-preference/earnings/master?q=SELECT+*%0AFROM+%60earnings_calendar%60%0AWHERE++%60date%60+%3E+%272000-12-31%27%0AAND+%60act_symbol%60+%3D+%27{ticker}%27%0AORDER+BY+%60date%60+ASC%3B%0A"
    # Make the HTTP GET request
    response = requests.get(url)

    # Check if the request was successful
    if response.status_code == 200:
        # Parse the JSON response
        data = response.json()

        # Check if the data contains 'rows' key
        if 'rows' in data and data['rows']:
            # Convert the list of dictionaries to a DataFrame
            df = pd.DataFrame(data['rows'])

            # Convert the DataFrame to a CSV string
            csv_buffer = StringIO()
            df.to_csv(csv_buffer, index = False)

            display(df.head(5))

            # Define the S3 location
            key = f'dolthub/finance-api/earnings/earnings_{ticker}_{datetime.datetime.now()}.csv'
        
            # Upload the CSV string to S3
            #s3_client.put_object(Body=csv_buffer.getvalue(), Bucket=bucket_name, Key=key)
            print(f"{ticker} saved")
    
        else:
            print("No data found in the response.")

    else:
        print("Failed to retrieve data: Status code", response.status_code)

    
    return

In [77]:
ticker_list = ["NVDA", "AAPL", "PLTR", "MSFT", "GOOGL", "PSTG", "TSLA"]

for ticker in ticker_list:
    
    save_dolthub_earnings_data(ticker)

  act_symbol        date                when
0       NVDA  2021-05-26  After market close
1       NVDA  2021-08-18  After market close
2       NVDA  2021-11-17  After market close
3       NVDA  2022-02-16  After market close
4       NVDA  2022-05-25  After market close

NVDA saved

  act_symbol        date                when
0       AAPL  2021-04-28  After market close
1       AAPL  2021-07-27  After market close
2       AAPL  2021-10-28  After market close
3       AAPL  2022-04-28  After market close
4       AAPL  2022-07-28  After market close

AAPL saved

  act_symbol        date                when
0       PLTR  2021-05-11  Before market open
1       PLTR  2021-08-12  Before market open
2       PLTR  2021-11-09  Before market open
3       PLTR  2022-02-17  Before market open
4       PLTR  2022-05-09  Before market open

PLTR saved

  act_symbol        date                when
0       MSFT  2021-04-27  After market close
1       MSFT  2021-07-27  After market close
2       MSFT  2021-10-26  After market close
3       MSFT  2022-04-26  After market close
4       MSFT  2022-07-26  After market close

MSFT saved

  act_symbol        date                when
0      GOOGL  2021-04-27  After market close
1      GOOGL  2021-07-27  After market close
2      GOOGL  2021-10-26  After market close
3      GOOGL  2022-02-01  After market close
4      GOOGL  2022-04-26  After market close

GOOGL saved

  act_symbol        date                when
0       PSTG  2021-05-26  After market close
1       PSTG  2021-08-25  After market close
2       PSTG  2021-11-23  After market close
3       PSTG  2022-03-02  After market close
4       PSTG  2022-06-01  After market close

PSTG saved

  act_symbol        date                when
0       TSLA  2021-04-26  After market close
1       TSLA  2021-07-26  After market close
2       TSLA  2021-10-20  After market close
3       TSLA  2022-04-20  After market close
4       TSLA  2022-07-20  After market close

TSLA saved

In [72]:
csv_buffer

In [73]:
df

   act_symbol        date                when
0        TSLA  2021-04-26  After market close
1        TSLA  2021-07-26  After market close
2        TSLA  2021-10-20  After market close
3        TSLA  2022-04-20  After market close
4        TSLA  2022-07-20  After market close
5        TSLA  2022-10-19  After market close
6        TSLA  2023-01-25  After market close
7        TSLA  2023-04-19  After market close
8        TSLA  2023-07-19  After market close
9        TSLA  2023-10-18  After market close
10       TSLA  2024-01-24  After market close
11       TSLA  2024-04-23  After market close